text_color=D8DEE9
background_color=020202
background_alpha=0.4
round_corners=5
engine_short_names
font_file_text=/usr/share/fonts/gnu-free/FreeSansBold.ttf
font_glyph_ranges=cyrillic

output_folder=/home/kray

toggle_hud=Shift_R+F12
toggle_hud_position=Shift_R+F11

#mangoapp_steam

#vulkan_present_mode=immediate

legacy_layout=0

gpu_color=A3BE8C
gpu_load_value=50,90
gpu_load_color=D8DEE9,D08770,BF616A
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
#gpu_power
gpu_load_change

vram_color=A3BE8C
proc_vram
vram

ram_color=BF616A
ram
swap

cpu_color=BF616A
cpu_load_value=50,90
cpu_load_color=D8DEE9,D08770,BF616A
cpu_stats
cpu_temp
core_load
#cpu_power
cpu_mhz
core_bars
cpu_load_change

fps
fps_metrics=0.01,0.001

engine_color=88C0D0
engine_version

frame_timing=1
frametime_color=88C0D0

wine_color=88C0D0
wine
winesync

resolution
gamemode
vkbasalt
display_server
present_mode

# gamescope only
refresh_rate
fsr
hdr

device_battery_icon
device_battery=gamepad

media_player
media_player_format={artist};{title}

blacklist=EpicGamesLauncher.exe,EpicWebHelper.exe
